### ISSUE TITLE
demo_cpm_hand.py does not work.

### ISSUE THREAD

**Issue by JungmoKoo** [timctho/convolutional-pose-machines-tensorflow#12]
I just download your project and run the 'demo_cpm_hand.py'.
But It does not work.
Line 106 should be replaced "model = cpm_hand.CPM_Model(FLAGS.input_size, FLAGS.hmap_size, FLAGS.stages, FLAGS.joints + 1)" and line 107 should be removed.
But I do not know how to fix it from now on.

**Comment by gabrielrlp** [comment]
$ **python3 run_demo_hand_with_tracker.py**

If you get some errors please update your OpenCV.
See that: [](https://github.com/BVLC/caffe/wiki/OpenCV-3.2-Installation-Guide-on-Ubuntu-16.04)
