### ISSUE TITLE
no "Ensemble_data_generator" 

### ISSUE THREAD

**Issue by guozhongluo** [timctho/convolutional-pose-machines-tensorflow#13]
I can't find "Ensemble_data_generator" in your code

**Comment by timctho** [comment]
It's related to my private dataset, please write your own data generator.

**Comment by LuisFernandoBecker** [comment]
Hey @timctho , we are having some problems training our custom cpm model and we are trying to replicate your training script. Could you explain what is the "Ensemble_data_generator" and how can we write it for our dataset? Thanks!
