### ISSUE TITLE
why i can not reach 30FPS?

### ISSUE THREAD

**Issue by JiangLinjunbupt** [timctho/convolutional-pose-machines-tensorflow#17]
i also run on an NVIDA  gpu , but i only get 5 FPS....may you tell me your tensorflow environment? or can you give me some suggestions?

**Comment by timctho** [comment]
please check if you install gpu version of tensoflow and CUDA.

**Comment by JiangLinjunbupt** [comment]
yes i have installed tensorflow-gpu and CUDA -8, cudnn6。 and i run on an NVIDA gpu ,the result shows only 5FPS.

i have also run on cpu，the fps is extremely low..... only 0.16FPS.

may be my gpu is not good enough, a better gpu is needed. @timctho

**Comment by timctho** [comment]
which gpu do you use?

**Comment by JiangLinjunbupt** [comment]
NVIDIA GeForce 1060 on my laptop......i'm sorry so late to reply. @timctho

**Comment by timctho** [comment]
I use gtx 1070, so shouldn't have so much difference in hardware aspect

**Comment by JiangLinjunbupt** [comment]
well, there may be some other problems i need to find by myself.... thx for your time :) @timctho
