### ISSUE TITLE
Some problem of training

### ISSUE THREAD

**Issue by Metal-joker** [timctho/convolutional-pose-machines-tensorflow#24]
I used `create_cpm_tfr_fulljoints.py` create TFRecord correctly, but I can't find how to use it in train script.
Any help?

**Comment by Metal-joker** [comment]
Or, Can you just update your data generator module? It will be very helpful!

**Comment by qingguoxu** [comment]
I don't know how to use the tfrecord file too. Also, in the run_taining.py file, the  Ensemble_data_generator module is missing.
