### ISSUE TITLE
How should I train CPM for MPII dataset? 

### ISSUE THREAD

**Issue by monajalal** [timctho/convolutional-pose-machines-tensorflow#26]
Please provide instruction on how to train CPM for MPII human pose dataset.
Also, do you have the model checkpoints for this dataset?

**Comment by A7ocin** [comment]
Can you please reopen this issue? I'm interested in it as well, thanks

**Comment by S-Altman** [comment]
> Can you please reopen this issue? I'm interested in it as well, thanks

Its July now, do you know how to train CPM for MPII human pose dataset

**Comment by S-Altman** [comment]
> Please provide instruction on how to train CPM for MPII human pose dataset.
> Also, do you have the model checkpoints for this dataset?

do you know how to train CPM for MPII human pose dataset now, appreciate your response
