### ISSUE TITLE
How can performance be improved ?

### ISSUE THREAD

**Issue by orgicus** [timctho/convolutional-pose-machines-tensorflow#33]
Hi,

Thank you for sharing the repository.
It's great there's a demo ready to run already.

Unfortunately I ran into some (memory) issues with TensorFlow 1.6 with (a 2GB) GPU.
I could run the demo using TensorFlow 1.4 CPU, but I get about 1fps.
I've tried reducing the webcam resolution as much as possible, but got no visible improvements.

How did you manage to get ~40fps ?

Thank you,
George

**Comment by asifzhcet11** [comment]
Hi George,

First you should first install the GPU version of the TensorFlow and run it. For me with GPU version the FPS is around 45 :)

Thanks!

Asif

**Comment by orgicus** [comment]
Hi @asifzhcet11 

Thank you very much for the feedback.
I'll try to compile TensorFlow 1.4 with GPU support on OSX and see how I fare.

By any chance have you tried exporting the model for Android ?

Thank you,
George

**Comment by asifzhcet11** [comment]
Hi George,

The macbook normally comes with an AMD GPU which is **not** supported by Tensorflow yet. So you have to test this on machines with Nvidia GPU.

And I haven't tried to work with this model for Android

Thanks!

Asif

**Comment by orgicus** [comment]
Hi Asif,

Thanks again for the clarifications.

I'm using an older macbook with a 2GB nVidia GPU.
It's a shame I got OOM errors with Tensorflow 1.6 GPU version.
(Will have to build Tensorflow 1.6 GPU from source)
What GPU are you using ?

Many thanks,
George

**Comment by asifzhcet11** [comment]
Hi George,
Did you install the correct CUDA and cuDNN version for your GPU. You can give it a try by using conda and the installing below package for the complete installation of TensorFlow 1.4 with CUDA and cuDNN

**conda install -c cjj3779 tensorflow-gpu**
 
https://anaconda.org/cjj3779/tensorflow-gpu

I am using GeForce GTX 1080

Thanks!

Asif

**Comment by orgicus** [comment]
Hi Asif,

I'm using CUDA 8.0.61 and cuDNN 5.1.10.

I can't use `pip` nor `conda` to install tensorflow-gpu as I'm using OSX and these options work only on Windows and Linux.

At the moment I can only think of compiling tensorflow 1.4 with GPU support from source just to test if I can get close to 40fps.

Thank you,
George

**Comment by asifzhcet11** [comment]
Hi George,

Please install conda as described below in the link and I hope you will be good to go :)

https://conda.io/docs/user-guide/install/macos.html

Thanks!

Asif

**Comment by kautukkundan** [comment]
Hello everyone
I am using a GTX 960 card but I still get about 4FPS

I have correctly set up CUDA and CUDnn
even nvidia-smi shows 3.7Gigs usage in GPU

can i do something to get better frame rates?

**Comment by zhengqinwen97** [comment]
> Hello everyone
> I am using a GTX 960 card but I still get about 4FPS
> 
> I have correctly set up CUDA and CUDnn
> even nvidia-smi shows 3.7Gigs usage in GPU
> 
> can i do something to get better frame rates?
It is impossible, I am using GTX960M with about 12FPS, maybe you should Set FLAG to the correct parameter

**Comment by DilaraAlbayrak** [comment]
Hi, I am running the code on ubuntu 16.04, I can run the code with tensorflow. I download tensorflow-gpu by using **conda install -c cjj3779 tensorflow-gpu** but, I have 'ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory' error. How can I run the code with tensorflow gpu?

**Comment by asifzhcet11** [comment]
Hi @DilaraSina 

It could be because of the path and library path is not set to the cuda 8.0 specific directories. If not present just add the path and give it a try.

Thanks,
Asif

**Comment by DilaraAlbayrak** [comment]
Thanks, I run on gpu and reached ~35 fps

**Comment by liang0724s** [comment]
Hi, @asifzhcet11 
I'm sorry to trouble you. Do you know where I can get the training data ,I want to retraining cpm_hand model.

**Comment by asifzhcet11** [comment]
Hi @liang0724s,

Below is the dataset I believe is used. I am not certainly sure but the guys who developed the convolution pose machines are from the same university and used datasets from the below resource. 

http://domedb.perception.cs.cmu.edu/handdb.html

Thanks,
Asif

**Comment by liang0724s** [comment]
> Hi @liang0724s,
> 
> Below is the dataset I believe is used. I am not certainly sure but the guys who developed the convolution pose machines are from the same university and used datasets from the below resource.
> 
> http://domedb.perception.cs.cmu.edu/handdb.html
> 
> Thanks,
> Asif

Hi @asifzhcet11

Thank you very much for the feedback.

Leo

**Comment by liang0724s** [comment]
> Hello everyone
> I am using a GTX 960 card but I still get about 4FPS
> 
> I have correctly set up CUDA and CUDnn
> even nvidia-smi shows 3.7Gigs usage in GPU
> 
> can i do something to get better frame rates?



> > Hello everyone
> > I am using a GTX 960 card but I still get about 4FPS
> > I have correctly set up CUDA and CUDnn
> > even nvidia-smi shows 3.7Gigs usage in GPU
> > can i do something to get better frame rates?
> > It is impossible, I am using GTX960M with about 12FPS, maybe you should Set FLAG to the correct parameter

Hi @kautukkundan ,
Did get a better frame rates by setting FLAG to the correct parameter ? 

Hi @jgjxzqw ,
The compute capability of GTX 960 and GTX960M respectively are 5.2 and 5.0, the performance is not very bad,  why the frame rate is so low?
 I am using GT720M with about 2FPS, and its compute capability is 2.1.
