### ISSUE TITLE
Can it detect two hands at the same time?

### ISSUE THREAD

**Issue by liaowang0125** [timctho/convolutional-pose-machines-tensorflow#4]
I tried, but it seems it just detect one hand at a time

**Comment by timctho** [comment]
No it can't. A naive way to do this is run a hand detector like YOLO or SSD, and feed each hand image into CPM model.

**Comment by liaowang0125** [comment]
ok

**Comment by liaowang0125** [comment]
I find that if there is no hand in the picture , there is still a random detection,because of choosing a max value from the last heatmap . So if there is a threshold in the last heatmap , when threshold is lower than a value, means no hand in the picture.

**Comment by liaowang0125** [comment]
Is keypoints in right hand more accurate than left hand? (In the same background)
@timctho
